package Test;

import SearchEngineTools.ParsingTools.Parse;
import SearchEngineTools.ParsingTools.ParseWithStemming;
import SearchEngineTools.ParsingTools.Term.ATerm;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

public class MyTest {
    public static void main(String[] args){
        String query = "<top>\n" +
                "\n" +
                "<num> Number: 351 \n" +
                "<title> Falkland petroleum explorationn \n" +
                "\n" +
                "<desc> Description: \n" +
                "What information is available on petroleum exploration in \n" +
                "the South Atlantic near the Falkland Islands?\n" +
                "\n" +
                "<narr> Narrative: \n" +
                "Any document discussing petroleum exploration in the\n" +
                "South Atlantic near the Falkland Islands is considered\n" +
                "relevant.  Documents discussing petroleum exploration in \n" +
                "continental South America are not relevant.\n" +
                "\n" +
                "</top>";

        List<String> queryAsList = new ArrayList<>();
        String[] splitQuery = query.split("\n");
        for (int i = 0; i < splitQuery.length; i++) {
            queryAsList.add(i,splitQuery[i]);
        }

        Parse parse = new ParseWithStemming();
        parse.setStopWords(getStopWords());
        Collection<ATerm> parsedQuery = parse.parseQuery(queryAsList,true,3);
       for (ATerm term:parsedQuery) {
            System.out.println(term);
        }
    }

    private static List<String> getStopWords(){

        String stopWords = "a\n" +
                "a's\n" +
                "able\n" +
                "about\n" +
                "above\n" +
                "according\n" +
                "accordingly\n" +
                "across\n" +
                "actually\n" +
                "after\n" +
                "afterwards\n" +
                "again\n" +
                "against\n" +
                "ain't\n" +
                "all\n" +
                "allow\n" +
                "allows\n" +
                "almost\n" +
                "alone\n" +
                "along\n" +
                "already\n" +
                "also\n" +
                "although\n" +
                "always\n" +
                "am\n" +
                "among\n" +
                "amongst\n" +
                "an\n" +
                "and\n" +
                "another\n" +
                "any\n" +
                "anybody\n" +
                "anyhow\n" +
                "anyone\n" +
                "anything\n" +
                "anyway\n" +
                "anyways\n" +
                "anywhere\n" +
                "apart\n" +
                "appear\n" +
                "appreciate\n" +
                "appropriate\n" +
                "are\n" +
                "aren't\n" +
                "around\n" +
                "as\n" +
                "aside\n" +
                "ask\n" +
                "asking\n" +
                "associated\n" +
                "at\n" +
                "available\n" +
                "away\n" +
                "awfully\n" +
                "b\n" +
                "be\n" +
                "became\n" +
                "because\n" +
                "become\n" +
                "becomes\n" +
                "becoming\n" +
                "been\n" +
                "before\n" +
                "beforehand\n" +
                "behind\n" +
                "being\n" +
                "believe\n" +
                "below\n" +
                "beside\n" +
                "besides\n" +
                "best\n" +
                "better\n" +
                "between\n" +
                "beyond\n" +
                "both\n" +
                "brief\n" +
                "but\n" +
                "by\n" +
                "c\n" +
                "c'mon\n" +
                "c's\n" +
                "came\n" +
                "can\n" +
                "can't\n" +
                "cannot\n" +
                "cant\n" +
                "cause\n" +
                "causes\n" +
                "certain\n" +
                "certainly\n" +
                "changes\n" +
                "clearly\n" +
                "co\n" +
                "com\n" +
                "come\n" +
                "comes\n" +
                "concerning\n" +
                "consequently\n" +
                "consider\n" +
                "considering\n" +
                "contain\n" +
                "containing\n" +
                "contains\n" +
                "corresponding\n" +
                "could\n" +
                "couldn't\n" +
                "course\n" +
                "currently\n" +
                "d\n" +
                "definitely\n" +
                "described\n" +
                "despite\n" +
                "did\n" +
                "didn't\n" +
                "different\n" +
                "do\n" +
                "does\n" +
                "doesn't\n" +
                "doing\n" +
                "don't\n" +
                "done\n" +
                "down\n" +
                "downwards\n" +
                "during\n" +
                "e\n" +
                "each\n" +
                "edu\n" +
                "eg\n" +
                "eight\n" +
                "either\n" +
                "else\n" +
                "elsewhere\n" +
                "enough\n" +
                "entirely\n" +
                "especially\n" +
                "et\n" +
                "etc\n" +
                "even\n" +
                "ever\n" +
                "every\n" +
                "everybody\n" +
                "everyone\n" +
                "everything\n" +
                "everywhere\n" +
                "ex\n" +
                "exactly\n" +
                "example\n" +
                "except\n" +
                "f\n" +
                "far\n" +
                "few\n" +
                "fifth\n" +
                "first\n" +
                "five\n" +
                "followed\n" +
                "following\n" +
                "follows\n" +
                "for\n" +
                "former\n" +
                "formerly\n" +
                "forth\n" +
                "four\n" +
                "from\n" +
                "further\n" +
                "furthermore\n" +
                "g\n" +
                "get\n" +
                "gets\n" +
                "getting\n" +
                "given\n" +
                "gives\n" +
                "go\n" +
                "goes\n" +
                "going\n" +
                "gone\n" +
                "got\n" +
                "gotten\n" +
                "greetings\n" +
                "h\n" +
                "had\n" +
                "hadn't\n" +
                "happens\n" +
                "hardly\n" +
                "has\n" +
                "hasn't\n" +
                "have\n" +
                "haven't\n" +
                "having\n" +
                "he\n" +
                "he's\n" +
                "hello\n" +
                "help\n" +
                "hence\n" +
                "her\n" +
                "here\n" +
                "here's\n" +
                "hereafter\n" +
                "hereby\n" +
                "herein\n" +
                "hereupon\n" +
                "hers\n" +
                "herself\n" +
                "hi\n" +
                "him\n" +
                "himself\n" +
                "his\n" +
                "hither\n" +
                "hopefully\n" +
                "how\n" +
                "howbeit\n" +
                "however\n" +
                "i\n" +
                "i'd\n" +
                "i'll\n" +
                "i'm\n" +
                "i've\n" +
                "ie\n" +
                "if\n" +
                "ignored\n" +
                "immediate\n" +
                "in\n" +
                "inasmuch\n" +
                "inc\n" +
                "indeed\n" +
                "indicate\n" +
                "indicated\n" +
                "indicates\n" +
                "inner\n" +
                "insofar\n" +
                "instead\n" +
                "into\n" +
                "inward\n" +
                "is\n" +
                "isn't\n" +
                "it\n" +
                "it'd\n" +
                "it'll\n" +
                "it's\n" +
                "its\n" +
                "itself\n" +
                "j\n" +
                "just\n" +
                "k\n" +
                "keep\n" +
                "keeps\n" +
                "kept\n" +
                "know\n" +
                "knows\n" +
                "known\n" +
                "l\n" +
                "last\n" +
                "lately\n" +
                "later\n" +
                "latter\n" +
                "latterly\n" +
                "least\n" +
                "less\n" +
                "lest\n" +
                "let\n" +
                "let's\n" +
                "like\n" +
                "liked\n" +
                "likely\n" +
                "little\n" +
                "look\n" +
                "looking\n" +
                "looks\n" +
                "ltd\n" +
                "m\n" +
                "mainly\n" +
                "many\n" +
                "may\n" +
                "maybe\n" +
                "me\n" +
                "mean\n" +
                "meanwhile\n" +
                "merely\n" +
                "might\n" +
                "more\n" +
                "moreover\n" +
                "most\n" +
                "mostly\n" +
                "much\n" +
                "must\n" +
                "my\n" +
                "myself\n" +
                "n\n" +
                "name\n" +
                "namely\n" +
                "nd\n" +
                "near\n" +
                "nearly\n" +
                "necessary\n" +
                "need\n" +
                "needs\n" +
                "neither\n" +
                "never\n" +
                "nevertheless\n" +
                "new\n" +
                "next\n" +
                "nine\n" +
                "no\n" +
                "nobody\n" +
                "non\n" +
                "none\n" +
                "noone\n" +
                "nor\n" +
                "normally\n" +
                "not\n" +
                "nothing\n" +
                "novel\n" +
                "now\n" +
                "nowhere\n" +
                "o\n" +
                "obviously\n" +
                "of\n" +
                "off\n" +
                "often\n" +
                "oh\n" +
                "ok\n" +
                "okay\n" +
                "old\n" +
                "on\n" +
                "once\n" +
                "one\n" +
                "ones\n" +
                "only\n" +
                "onto\n" +
                "or\n" +
                "other\n" +
                "others\n" +
                "otherwise\n" +
                "ought\n" +
                "our\n" +
                "ours\n" +
                "ourselves\n" +
                "out\n" +
                "outside\n" +
                "over\n" +
                "overall\n" +
                "own\n" +
                "p\n" +
                "particular\n" +
                "particularly\n" +
                "per\n" +
                "perhaps\n" +
                "placed\n" +
                "please\n" +
                "plus\n" +
                "possible\n" +
                "presumably\n" +
                "probably\n" +
                "provides\n" +
                "q\n" +
                "que\n" +
                "quite\n" +
                "qv\n" +
                "r\n" +
                "rather\n" +
                "rd\n" +
                "re\n" +
                "really\n" +
                "reasonably\n" +
                "regarding\n" +
                "regardless\n" +
                "regards\n" +
                "relatively\n" +
                "respectively\n" +
                "right\n" +
                "s\n" +
                "said\n" +
                "same\n" +
                "saw\n" +
                "say\n" +
                "saying\n" +
                "says\n" +
                "second\n" +
                "secondly\n" +
                "see\n" +
                "seeing\n" +
                "seem\n" +
                "seemed\n" +
                "seeming\n" +
                "seems\n" +
                "seen\n" +
                "self\n" +
                "selves\n" +
                "sensible\n" +
                "sent\n" +
                "serious\n" +
                "seriously\n" +
                "seven\n" +
                "several\n" +
                "shall\n" +
                "she\n" +
                "should\n" +
                "shouldn't\n" +
                "since\n" +
                "six\n" +
                "so\n" +
                "some\n" +
                "somebody\n" +
                "somehow\n" +
                "someone\n" +
                "something\n" +
                "sometime\n" +
                "sometimes\n" +
                "somewhat\n" +
                "somewhere\n" +
                "soon\n" +
                "sorry\n" +
                "specified\n" +
                "specify\n" +
                "specifying\n" +
                "still\n" +
                "sub\n" +
                "such\n" +
                "sup\n" +
                "sure\n" +
                "t\n" +
                "t's\n" +
                "take\n" +
                "taken\n" +
                "tell\n" +
                "tends\n" +
                "th\n" +
                "than\n" +
                "thank\n" +
                "thanks\n" +
                "thanx\n" +
                "that\n" +
                "that's\n" +
                "thats\n" +
                "the\n" +
                "their\n" +
                "theirs\n" +
                "them\n" +
                "themselves\n" +
                "then\n" +
                "thence\n" +
                "there\n" +
                "there's\n" +
                "thereafter\n" +
                "thereby\n" +
                "therefore\n" +
                "therein\n" +
                "theres\n" +
                "thereupon\n" +
                "these\n" +
                "they\n" +
                "they'd\n" +
                "they'll\n" +
                "they're\n" +
                "they've\n" +
                "think\n" +
                "third\n" +
                "this\n" +
                "thorough\n" +
                "thoroughly\n" +
                "those\n" +
                "though\n" +
                "three\n" +
                "through\n" +
                "throughout\n" +
                "thru\n" +
                "thus\n" +
                "to\n" +
                "together\n" +
                "too\n" +
                "took\n" +
                "toward\n" +
                "towards\n" +
                "tried\n" +
                "tries\n" +
                "truly\n" +
                "try\n" +
                "trying\n" +
                "twice\n" +
                "two\n" +
                "u\n" +
                "un\n" +
                "under\n" +
                "unfortunately\n" +
                "unless\n" +
                "unlikely\n" +
                "until\n" +
                "unto\n" +
                "up\n" +
                "upon\n" +
                "us\n" +
                "use\n" +
                "used\n" +
                "useful\n" +
                "uses\n" +
                "using\n" +
                "usually\n" +
                "uucp\n" +
                "v\n" +
                "value\n" +
                "various\n" +
                "very\n" +
                "via\n" +
                "viz\n" +
                "vs\n" +
                "w\n" +
                "want\n" +
                "wants\n" +
                "was\n" +
                "wasn't\n" +
                "way\n" +
                "we\n" +
                "we'd\n" +
                "we'll\n" +
                "we're\n" +
                "we've\n" +
                "welcome\n" +
                "well\n" +
                "went\n" +
                "were\n" +
                "weren't\n" +
                "what\n" +
                "what's\n" +
                "whatever\n" +
                "when\n" +
                "whence\n" +
                "whenever\n" +
                "where\n" +
                "where's\n" +
                "whereafter\n" +
                "whereas\n" +
                "whereby\n" +
                "wherein\n" +
                "whereupon\n" +
                "wherever\n" +
                "whether\n" +
                "which\n" +
                "while\n" +
                "whither\n" +
                "who\n" +
                "who's\n" +
                "whoever\n" +
                "whole\n" +
                "whom\n" +
                "whose\n" +
                "why\n" +
                "will\n" +
                "willing\n" +
                "wish\n" +
                "with\n" +
                "within\n" +
                "without\n" +
                "won't\n" +
                "wonder\n" +
                "would\n" +
                "would\n" +
                "wouldn't\n" +
                "x\n" +
                "y\n" +
                "yes\n" +
                "yet\n" +
                "you\n" +
                "you'd\n" +
                "you'll\n" +
                "you're\n" +
                "you've\n" +
                "your\n" +
                "yours\n" +
                "yourself\n" +
                "yourselves\n" +
                "z\n" +
                "zero";
        return Arrays.asList(stopWords.split("\n"));
    }
}
